title: "Haodong Yang"
author: "Haodong Yang"
description: "Syracuse University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About me", sidebaricon: address-card}
  - {url: "/HaodongYang.pdf", title: "CV", sidebaricon: file-pdf}
  - {file: "publications.md", title: "Publications", sidebaricon: book}
  - {file: "quantum-notes.md", title: "Quantum Notes", sidebaricon: flask}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:yanghaodong22@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/a5210467"}

  

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
